# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
      - main
  paths:
   include:
     - Scraper/*
     - azure-pipelines-scraper.yml

pool:
  vmImage: 'windows-latest'
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactPath: '$(System.DefaultWorkingDirectory)/drop'
  project: './Scraper/Scraper.csproj'

steps:


- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    arguments: '-c $(buildConfiguration) -o $(artifactPath)'
    modifyOutputPath: false

- publish: '$(artifactPath)'
  artifact: Scraper