// <auto-generated />
using System;
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Data.Migrations
{
    [DbContext(typeof(FoodContext))]
    partial class FoodContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Data.Types.FoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<double>("Per")
                        .HasColumnType("double precision");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("Core.Data.Types.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Core.Data.Types.NutritionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fats")
                        .HasColumnType("double precision");

                    b.Property<double?>("FatsSaturated")
                        .HasColumnType("double precision");

                    b.Property<double?>("FatsUnsaturated")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fibres")
                        .HasColumnType("double precision");

                    b.Property<int>("Per")
                        .HasColumnType("integer");

                    b.Property<int>("PerUnit")
                        .HasColumnType("integer");

                    b.Property<int?>("PortionRecommended")
                        .HasColumnType("integer");

                    b.Property<int?>("PreparationState")
                        .HasColumnType("integer");

                    b.Property<double?>("Proteines")
                        .HasColumnType("double precision");

                    b.Property<double?>("Salts")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sugars")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("NutritionInfos");
                });

            modelBuilder.Entity("Core.Data.Types.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nutriscore")
                        .HasColumnType("text");

                    b.Property<int?>("NutritionInfoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitSize")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NutritionInfoId")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Core.Data.Types.ProductScrapeJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("ScrapeJobs");
                });

            modelBuilder.Entity("ProductIngredients", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductsId")
                        .HasColumnType("integer");

                    b.HasKey("IngredientsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductIngredients");
                });

            modelBuilder.Entity("Core.Data.Types.FoodEntry", b =>
                {
                    b.HasOne("Core.Data.Types.Product", "Product")
                        .WithMany("FoodEntries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Data.Types.Product", b =>
                {
                    b.HasOne("Core.Data.Types.NutritionInfo", "NutritionInfo")
                        .WithOne("Product")
                        .HasForeignKey("Core.Data.Types.Product", "NutritionInfoId");

                    b.Navigation("NutritionInfo");
                });

            modelBuilder.Entity("Core.Data.Types.ProductScrapeJob", b =>
                {
                    b.HasOne("Core.Data.Types.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductIngredients", b =>
                {
                    b.HasOne("Core.Data.Types.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Data.Types.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Data.Types.NutritionInfo", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Data.Types.Product", b =>
                {
                    b.Navigation("FoodEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
